version: "3.9"
services:
  discobot:
    image: fabrzy/discobot:v3
    container_name: discobot
    restart: always
    environment:
      OAI_SECRET: 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
      DISCOSECRET: uRgP2O9n2UJVsvuMX3oIybiYK22ALFof
      CLIENT_ID: 1115487825597562910
      DISCO_TOKEN: MTExNTQ4NzgyNTU5NzU2MjkxMA.GfvsHD.OCI6mhMoVVZY3f2DHAHiKYVnZ_d3FbgRtF20vM
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
  
